const caseName = ["台積電植樹團隊於桃園市公有土地植樹",
"大安森林公園之友基金會投入大安森林公園的樹木健檢與小型濕地經營",
"大同公司南投、澎湖與桃園太陽能發電系統專案(B0000197)",
"吉安鄉干城社區太陽能光電照明系統",
"屏東基督教勝利之家-綠能公益屋頂",
"標準檢驗局花蓮分局設置垂直軸風力機",
"臺南市私立德光高級中學-換裝高效率空調(B0000271-001)",
"財團法人崑山科技大學-換裝高效率燈具(B0000271-002)",
"金門縣政府節能燈具及路燈汰換溫室氣體減量專案(B0000076)",
"大安區公有建物設置光電設施",
"吉安鄉南華村公有建物設置光電設施",
"吉安圳小水力裝置設置",
"花蓮遊客中心評估小風機設施",
"吉安鄉干城村地區沼氣發電設施評估",
"臺南市七股鹽田濕地",
"臺南市仁德區-嘉南藥理科技大學人工濕地",
"臺灣大學校內水域及周邊環境(醉月湖、生態池、瑠公圳水路復育系統)",
"東華大學校內水域及周邊環境(東湖、華湖、小華湖)",
"木瓜溪華隆護岸及初英一號堤段河川環境與臺灣火刺木復育計畫",
"桃園市 2021 年可提供民間公益植樹公有土地",
"大安森林公園-公園生態化經營",
"知卡宣綠森林親水公園-公園生態化經營",
"南華林業園區-公園生態化經營",
"大安區山坡地保護區範圍經營措施",
"花蓮林管處吉安鄉與壽豐鄉範圍內的保安林與保育屬性國有林班地",
"花蓮林管處吉安鄉與壽豐鄉內屬於林木經營區之國有林班地",
"臺灣大學臺大農場 (土耕)",
"壽豐鄉養殖專區 (養殖魚塭)",
"花蓮縣初英山文化產業交流協會",
"大安區錦安里",
"新北市八里區-淨零碳示範區政策目標",
"花蓮縣鳳林鎮-國際慢城認證",
"東華大學總務處減碳小組",
"台大氣候行動社",
"舊空軍總部再開發案",
"台灣觀光學院學產地用地轉型-15.6公頃校地",
"捷運大安站周邊更新地區",
"花蓮縣第1期(吉安鄉住一住宅)自辦市地重市地重劃"];

const type = [
"已執行案例",
"已執行案例",
"已執行案例",
"已執行案例",
"已執行案例",
"已執行案例",
"已執行案例",
"已執行案例",
"已執行案例",
"設置再生能源",
"設置再生能源",
"設置再生能源",
"設置再生能源",
"設置再生能源",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"經營地景碳匯",
"社會共創模式",
"社會共創模式",
"社會共創模式",
"社會共創模式",
"社會共創模式",
"社會共創模式",
"土地開發評估",
"土地開發評估",
"土地開發評估",
"土地開發評估"];

const quota = [
14.81,
0,
8560,
0,
3.66,
0.03,
23,
4,
60,
13143,
91,
778,
0.16,
2.04,
65.8,
0.21,
0,
0,
40.8,
424,
386,
104.9,
195.9,
12480,
606816,
0,
8.45,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0];

const cost = [
500,
500,
20000,
100,
500,
200,
1000,
800,
1000,
20000,
1000,
2000,
500,
800,
2000,
500,
1000,
1000,
500,
8000,
800,
800,
800,
5000,
10000,
500,
800,
500,
100,
100,
500,
500,
500,
100,
200,
200,
500,
200
];


const means = [
"綠資源",
"綠資源",
"光電設施",
"光電設施",
"光電設施",
"小風機",
"設備經營管理",
"設備經營管理",
"設備經營管理",
"光電設施",
"光電設施",
"小水力",
"小風機",
"生質能",
"水環境",
"水環境",
"水環境",
"水環境",
"水環境",
"綠資源",
"綠資源",
"綠資源",
"綠資源",
"綠資源",
"綠資源",
"綠資源",
"再生農漁業",
"再生農漁業",
"低碳社區",
"低碳社區",
"地方創生",
"地方創生",
"大學合作",
"大學合作",
"園區開發",
"園區開發",
"都市更新",
"重劃區"];

const effect = [
"地區示範案例",
"地區示範案例",
"地區示範案例",
"地區示範案例",
"地區示範案例",
"地區示範案例",
"地區示範案例",
"地區示範案例",
"地區示範案例",
"可用於抵換專案的案場",
"可用於抵換專案的案場",
"可用於抵換專案的案場",
"可用於抵換專案的案場",
"可用於抵換專案的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"適合研發抵換方法的案場",
"推動低碳社區",
"推動低碳社區",
"結合地方創生",
"結合地方創生",
"推動永續校園",
"推動永續校園",
"落實低碳營建",
"落實低碳營建",
"落實低碳營建",
"落實低碳營建"];

const method = [
"無",
"無",
"AMS-I.D. 併網的可再生能源發電",
"無",
"無",
"無",
"AMS-II.C. 需求端利用特定技術的能源效率活動",
"AMS-II.C. 需求端利用特定技術的能源效率活動",
"AMS-II.L. 需求端: 高效率室外及街燈照明技術",
"AMS-I.D. 併網的可再生能源發電",
"AMS-I.D. 併網的可再生能源發電",
"AMS-I.L 鄉村社區再生能源電氣化",
"AMS-I.L 鄉村社區再生能源電氣化",
"AMS-I.L 鄉村社區再生能源電氣化",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無",
"無"];

const unit = [
"桃園市政府養護工程處",
"大安森林公園之友基金會",
"大同公司",
"花蓮縣初英山文化產業交流協會",
"台灣綠能公益發展協會",
"經濟部標準檢驗局花蓮分局",
"臺南市政府環境保護局",
"臺南市政府環境保護局",
"金門縣政府",
"臺北市政府產業發展局公用事業科",
"花蓮縣觀光處工業管理科",
"花蓮縣初英山文化產業交流協會",
"交通部觀光局東部海岸國家風景區管理處花蓮遊客中心",
"行政院農業委員會畜產試驗所花蓮種畜繁殖場",
"內政部營建署城鄉發展分署",
"嘉南藥理科技大學",
"國立臺灣大學",
"國立東華大學",
"經濟部水利署第九河川局",
"桃園市政府養護工程處",
"臺北市政府工務局公園路燈工程管理處",
"花蓮縣政府吉安鄉公所",
"林務局花蓮林區管理處",
"臺北市政府大安區公所",
"林務局花蓮林區管理處",
"林務局花蓮林區管理處",
"國立臺灣大學",
"花蓮縣養殖漁業生產區發展協會",
"花蓮縣初英山文化產業交流協會",
"臺北市大安區錦安里辦公處",
"新北市政府八里區公所",
"花蓮縣鳳林鎮北林三村社區發展協會",
"國立東華大學",
"台大氣候行動社",
"文化部",
"教育部",
"臺北市政府都市更新處",
"花蓮縣政府地政處"];

const link = [
"https://www.tycg.gov.tw/ch/home.jsp?id=10412&parentpath=0,10401&mcustomize=news_view.jsp&dataserno=202103120001&aplistdn=ou=news,ou=chinese,ou=ap_root,o=tycg,c=tw&toolsflag=Y",
"https://www.daanforestpark.org.tw/",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblEsxVIPFrCC1azI/viwiGpK0F1lONnvpa/recovpBrV0OZsww2J?blocks=hide",
"http://sixstar.moc.gov.tw/blog/u120109593/communityResultListAction.do?method=doRead&type=1&resultId=29060",
"https://www.sunnyfounder.com/charity/vhome",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblJjkyRlbGH4dSGH/viwjQ8KO5LcIjheno/recEVQiLTSrDHzOWa?blocks=hide",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblEsxVIPFrCC1azI/viwiGpK0F1lONnvpa/recz06IefO4YeMuFr?blocks=hide",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblEsxVIPFrCC1azI/viwiGpK0F1lONnvpa/recnC2jNPTsIEkWuA?blocks=hide",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblEsxVIPFrCC1azI/viwiGpK0F1lONnvpa/rechoaJqQwqpvTANf?blocks=hide",
"https://goo.gl/maps/p3BS5zpA2eaFVaTv6",
"https://goo.gl/maps/p3BS5zpA2eaFVaTv6",
"http://sixstar.moc.gov.tw/blog/chuinsan/communityAction.do?method=doCommunityView",
"http://www.small-wind.org.tw/content/wind/wind_notice.aspx",
"https://www.biogas.com.tw/benefit/",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblEsxVIPFrCC1azI/viwiGpK0F1lONnvpa/recnr0e5n9HzzhUNm?blocks=hide",
"https://airtable.com/shrcpgvjxMsX7GIhw/tblEsxVIPFrCC1azI/viwiGpK0F1lONnvpa/reck6DXHrOMd8nbdj?blocks=hide",
"https://youtu.be/2VlgaDaxqi0?t=81",
"https://rb001.ndhu.edu.tw/p/132-1001-2245.php",
"https://www.wra.gov.tw/News_Content.aspx?n=6431&s=93748",
"https://www.tycg.gov.tw/ch/home.jsp?id=10412&parentpath=0,10401&mcustomize=news_view.jsp&dataserno=202103120001&aplistdn=ou=news,ou=chinese,ou=ap_root,o=tycg,c=tw&toolsflag=Y",
"https://youtube.com/playlist?list=PLLhKX7btG59cCUgTbgSV6sfBhOLqcgIm4",
"https://www.facebook.com/%E7%9F%A5%E5%8D%A1%E5%AE%A3%E7%B6%A0%E6%A3%AE%E6%9E%97%E8%A6%AA%E6%B0%B4%E5%85%AC%E5%9C%92-113463993763171/",
"https://tour-hualien.hl.gov.tw/POI/157",
"https://dado.gov.taipei/News.aspx?n=83E25322F56372E8&sms=DD0C9C3CF31B1E8E",
"https://hualien.forest.gov.tw/",
"https://hualien.forest.gov.tw/",
"https://www.farm.ntu.edu.tw/index.aspx?lang=TW",
"https://www.fish1996.com.tw/hualien-county.html",
"https://www.facebook.com/%E5%88%9D%E8%8B%B1%E5%B1%B1Mia-672808719483863/",
"https://lcss.epa.gov.tw/LcssViewPage/Responsive/AreaResult.aspx?CityID=63000&DistrictId=6300300&VillageID=6300300016",
"https://www.epd.ntpc.gov.tw/Journal/Content?c=11005&t=policy",
"https://2019smalltown.taiwan.net.tw/News/Detail/79779d97-e768-4c75-b5fd-0cf03c5317f5?CategoryId=a3130fe3-eabe-47a5-8826-ca8370b2be43",
"https://ga.ndhu.edu.tw/p/412-1006-13976.php?Lang=zh-tw",
"https://www.facebook.com/NTUClimateAction",
"https://clab.org.tw/about/",
"https://www.cna.com.tw/news/firstnews/202106050038.aspx",
"https://twur.cpami.gov.tw/zh/urban/area/view/506",
"https://la.hl.gov.tw/Detail_sp/cd893dc0e3c44ed980a74702e13662dc"];

caseName.forEach((name, index) => {
    console.log(`[${index+1}, {
        name: "${name}",
        type: "${type[index]}",
        quota: ${quota[index]},
        cost: ${cost[index]},
        means: "${means[index]}",
        effect: "${effect[index]}",
        method: "${method[index]}",
        unit: "${unit[index]}",
        link: "${link[index]}",
        comment: ""
    }],`);
});
